ALTER TABLE Person
ADD 
	ValidFrom datetime2(2) GENERATED ALWAYS AS ROW START CONSTRAINT defValidFrom DEFAULT SYSUTCDATETIME(),
	ValidTo datetime2(2) GENERATED ALWAYS AS ROW END CONSTRAINT defValidTo DEFAULT 
															CONVERT(datetime2(2),'9999-12-31 23:59:59'),
	PERIOD FOR SYSTEM_TIME(ValidFrom,ValidTo)
	--WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.tblPersonHistory))